examples/deltaspike-fullstack/src/main/java/org/superbiz/deltaspike/view/MenuBean.java
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.superbiz.deltaspike.view;

import org.apache.deltaspike.core.spi.scope.conversation.GroupedConversationManager;
import org.superbiz.deltaspike.view.config.Pages;

import javax.enterprise.inject.Model;
import javax.inject.Inject;

@Model
public class MenuBean
{
    @Inject
    private GroupedConversationManager groupedConversationManager;

    public Class<? extends Pages> home()
    {
        //close all conversations of the current window
        this.groupedConversationManager.closeConversations();
        return Pages.Index.class;
    }

    public Class<? extends Pages.Secure> feedback()
    {
        //close all conversations of the current window
        this.groupedConversationManager.closeConversations();
        return Pages.Secure.FeedbackList.class;
    }

    public Class<? extends Pages> about()
    {
        //close all conversations of the current window
        this.groupedConversationManager.closeConversations();
        return Pages.About.class;
    }

    public Class<? extends Pages> login()
    {
        //close all conversations of the current window
        this.groupedConversationManager.closeConversations();
        return Pages.Login.class;
    }

    public Class<? extends Pages> register()
    {
        //close all conversations of the current window
        this.groupedConversationManager.closeConversations();
        return Pages.Registration.class;
    }
}

examples/deltaspike-fullstack/src/main/java/org/superbiz/deltaspike/view/util/InfoBean.java
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.superbiz.deltaspike.view.util;

import org.apache.deltaspike.core.api.config.view.metadata.ViewConfigDescriptor;
import org.apache.deltaspike.core.api.config.view.metadata.ViewConfigResolver;
import org.apache.deltaspike.core.api.projectstage.ProjectStage;
import org.apache.deltaspike.core.api.provider.BeanManagerProvider;
import org.apache.deltaspike.core.spi.scope.window.WindowContext;
import org.apache.deltaspike.jsf.api.message.JsfMessage;
import org.apache.myfaces.extensions.validator.ExtValInformation;
import org.apache.myfaces.extensions.validator.util.ClassUtils;
import org.superbiz.deltaspike.WebappMessageBundle;
import org.superbiz.deltaspike.view.InfoPage;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.Persistence;
import javax.validation.Validation;
import java.io.Serializable;

@SuppressWarnings("CdiUnproxyableBeanTypesInspection")
@Named
@SessionScoped
public class InfoBean implements Serializable
{
    private static final long serialVersionUID = -1748909261695527800L;

    @Inject
    private WindowContext windowContext;

    @Inject
    private JsfMessage<WebappMessageBundle> webappMessages;

    @Inject
    private ProjectStage projectStage;

    @Inject
    private ViewConfigResolver viewConfigResolver;

    private String applicationMessageVersionInfo;

    private String beanValidationVersion;

    private String jpaVersion;

    @PostConstruct
    protected void showWelcomeMessage()
    {
        String versionString = ClassUtils.getJarVersion(InfoBean.class);

        if (versionString != null)
        {
            this.applicationMessageVersionInfo = " (v" + versionString + ")";
        }

        this.beanValidationVersion =
                ClassUtils.getJarVersion(Validation.buildDefaultValidatorFactory().getValidator().getClass());

        this.jpaVersion =
                ClassUtils.getJarVersion(Persistence.createEntityManagerFactory("demoApplicationPU").getClass());

        if (!ProjectStage.IntegrationTest.equals(this.projectStage))
        {
            this.webappMessages.addInfo().msgWelcome();
        }
    }

    public boolean isInfoPage()
    {
        ViewConfigDescriptor viewConfigDescriptor =
                this.viewConfigResolver.getViewConfigDescriptor(FacesContext.getCurrentInstance().getViewRoot().getViewId());

        if (viewConfigDescriptor == null)
        {
            return false;
        }

        return !viewConfigDescriptor.getMetaData(InfoPage.class).isEmpty();
    }

    public String getProjectStage()
    {
        return this.projectStage.toString();
    }

    public String getApplicationVersion()
    {
        return this.applicationMessageVersionInfo;
    }

    public String getDeltaSpikeVersion()
    {
        return ClassUtils.getJarVersion(BeanManagerProvider.class);
    }

    public String getCdiVersion()
    {
        return ClassUtils.getJarVersion(BeanManagerProvider.getInstance().getBeanManager().getClass());
    }

    public String getExtValVersion()
    {
        return ExtValInformation.VERSION;
    }

    public String getJsfVersion()
    {
        return ClassUtils.getJarVersion(FacesContext.class);
    }

    public String getBeanValidationVersion()
    {
        return this.beanValidationVersion;
    }

    public String getJpaVersion()
    {
        return this.jpaVersion;
    }

    public String getWindowId()
    {
        return this.windowContext.getCurrentWindowId();
    }
}

examples/deltaspike-fullstack/src/main/webapp/layout/main-template.xhtml
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.prime.com.tr/ui"
        >

<f:view contentType="text/html">

    <h:head>
        <title>Apache TomEE/DeltaSpike-Stack Demo</title>
        <h:outputStylesheet library="styles" name="base.css"/>
        <h:outputStylesheet library="styles" name="theme.css"/>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    </h:head>
    <h:body>
        <div id="header">
            <h:form id="topMenuForm" prependId="false">
                <div id="top_menu">
                    <div id="top_menu_container">
                        <h:panelGroup rendered="#{infoBean.infoPage}">
                            <div class="date">Apache TomEE/DeltaSpike-Stack <b>Demo-App</b> #{infoBean.applicationVersion}</div>
                        </h:panelGroup>
                        <div id="projectStage" class="date">[#{infoBean.projectStage}]</div>
                        <ul>
                            <li>
                                <h:commandLink id="lnkLogin" value="#{i18n.lnkLogin}" action="#{menuBean.login}"/>
                            </li>
                            <li>
                                <a href="http://www.apache.org" target="_blank">Apache</a>
                            </li>
                            <li>
                                <a href="http://deltaspike.apache.org" target="_blank">DeltaSpike</a>
                            </li>
                            <li>
                                <a href="http://myfaces.apache.org" target="_blank">MyFaces</a>
                            </li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                </div>
            </h:form>
            <div id="header_bottom">
                <div id="logo_banner_container">
                    <div id="logo">
                        <h1>
                            <a href="http://deltaspike.apache.org/">Apache DS</a>
                        </h1>
                    </div>
                    <div id="banner">
                        <!-- TODO add logo -->
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div id="main_container">
            <div id="left_column">
                <h:form id="menuForm" prependId="false">
                    <div class="left_menu_top">
                        <div class="left_menu_bottom">
                            <h5>#{i18n.lblLeftMenuTitle}</h5>

                            <div class="content">
                                <ul class="left_menu">
                                    <ui:include src="menu.xhtml"/>
                                </ul>
                            </div>
                        </div>
                    </div>
                </h:form>

                <div class="clear"></div>

                <h:form id="leftMenuForm" prependId="false">

                    <div class="left_menu_top">
                        <div class="left_menu_bottom">
                            <h5>#{i18n.menuMisc}</h5>

                            <div class="content">
                                <ul class="left_menu">
                                    <li class="none">
                                        <h:commandLink id="menuAbout" value="#{i18n.menuAbout}" action="#{menuBean.about}"/>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </h:form>
                <div class="clear"></div>
            </div>
            <div id="body_column">
                <div>
                    <div class="section">

                        <ui:insert name="header"><h2>Apache TomEE/DeltaSpike-Stack Demo-App</h2></ui:insert>

                        <div class="main_content">
                            <h:form id="mainForm" prependId="false">
                                <ui:insert name="content"><p>No content available.</p></ui:insert>
                            </h:form>
                        </div>

                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <p:growl sticky="false" showSummary="true" showDetail="false"/>
        <div id="footer">
            <div class="copyright">
                <p>&#169; The Apache Software Foundation
                </p>
            </div>
        </div>
    </h:body>
</f:view>
</html>

examples/deltaspike-fullstack/src/main/webapp/layout/menu.xhtml
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->
<div id="menu"
     xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
        >

    <li class="none">
        <h:commandLink id="menuHome" value="#{i18n.lblHome}" action="#{menuBean.home}"/>
    </li>

    <li class="none">
        <h:commandLink id="menuFeedback" value="#{i18n.lblFeedback}" action="#{menuBean.feedback}"/>
    </li>

</div>