examples/deltaspike-fullstack/src/main/java/org/superbiz/deltaspike/view/util/InfoBean.java
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.superbiz.deltaspike.view.util;

import org.apache.deltaspike.core.api.config.view.metadata.ViewConfigDescriptor;
import org.apache.deltaspike.core.api.config.view.metadata.ViewConfigResolver;
import org.apache.deltaspike.core.api.projectstage.ProjectStage;
import org.apache.deltaspike.core.api.provider.BeanManagerProvider;
import org.apache.deltaspike.core.spi.scope.window.WindowContext;
import org.apache.deltaspike.jsf.api.message.JsfMessage;
import org.apache.myfaces.extensions.validator.ExtValInformation;
import org.apache.myfaces.extensions.validator.util.ClassUtils;
import org.superbiz.deltaspike.WebappMessageBundle;
import org.superbiz.deltaspike.view.InfoPage;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.Persistence;
import javax.validation.Validation;
import java.io.Serializable;

@SuppressWarnings("CdiUnproxyableBeanTypesInspection")
@Named
@SessionScoped
public class InfoBean implements Serializable
{
    private static final long serialVersionUID = -1748909261695527800L;

    @Inject
    private WindowContext windowContext;

    @Inject
    private JsfMessage<WebappMessageBundle> webappMessages;

    @Inject
    private ProjectStage projectStage;

    @Inject
    private ViewConfigResolver viewConfigResolver;

    private String applicationMessageVersionInfo;

    private String beanValidationVersion;

    private String jpaVersion;

    @PostConstruct
    protected void showWelcomeMessage()
    {
        String versionString = ClassUtils.getJarVersion(InfoBean.class);

        if (versionString != null)
        {
            this.applicationMessageVersionInfo = " (v" + versionString + ")";
        }

        this.beanValidationVersion =
                ClassUtils.getJarVersion(Validation.buildDefaultValidatorFactory().getValidator().getClass());

        this.jpaVersion =
                ClassUtils.getJarVersion(Persistence.createEntityManagerFactory("demoApplicationPU").getClass());

        if (!ProjectStage.IntegrationTest.equals(this.projectStage))
        {
            this.webappMessages.addInfo().msgWelcome();
        }
    }

    public boolean isInfoPage()
    {
        ViewConfigDescriptor viewConfigDescriptor =
                this.viewConfigResolver.getViewConfigDescriptor(FacesContext.getCurrentInstance().getViewRoot().getViewId());

        if (viewConfigDescriptor == null)
        {
            return false;
        }

        return !viewConfigDescriptor.getMetaData(InfoPage.class).isEmpty();
    }

    public String getProjectStage()
    {
        return this.projectStage.toString();
    }

    public String getApplicationVersion()
    {
        return this.applicationMessageVersionInfo;
    }

    public String getDeltaSpikeVersion()
    {
        return ClassUtils.getJarVersion(BeanManagerProvider.class);
    }

    public String getCdiVersion()
    {
        return ClassUtils.getJarVersion(BeanManagerProvider.getInstance().getBeanManager().getClass());
    }

    public String getExtValVersion()
    {
        return ExtValInformation.VERSION;
    }

    public String getJsfVersion()
    {
        return ClassUtils.getJarVersion(FacesContext.class);
    }

    public String getBeanValidationVersion()
    {
        return this.beanValidationVersion;
    }

    public String getJpaVersion()
    {
        return this.jpaVersion;
    }

    public String getWindowId()
    {
        return this.windowContext.getCurrentWindowId();
    }
}

examples/deltaspike-fullstack/src/main/webapp/pages/about.xhtml
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/layout/main-template.xhtml">

    <ui:define name="content">
        <h:panelGrid columns="2">
            <h:outputLabel value="Current Window-ID:" for="wid"/>
            <h:outputText id="wid" value="#{infoBean.windowId}"/>

            <h:outputLabel value="Apache MyFaces-Core:" for="jsfVersion"/>
            <h:outputText id="jsfVersion" value="#{infoBean.jsfVersion}"/>

            <h:outputLabel value="Apache OpenWebBeans:" for="cdiVersion"/>
            <h:outputText id="cdiVersion" value="#{infoBean.cdiVersion}"/>

            <h:outputLabel value="Apache DeltaSpike:" for="dsVersion"/>
            <h:outputText id="dsVersion" value="#{infoBean.deltaSpikeVersion}"/>

            <h:outputLabel value="Apache MyFaces ExtVal:" for="extValVersion"/>
            <h:outputText id="extValVersion" value="#{infoBean.extValVersion}"/>

            <h:outputLabel value="Apache BVal:" for="bValVersion"/>
            <h:outputText id="bValVersion" value="#{infoBean.beanValidationVersion}"/>

            <h:outputLabel value="Apache OpenJPA:" for="jpaVersion"/>
            <h:outputText id="jpaVersion" value="#{infoBean.jpaVersion}"/>
        </h:panelGrid>
    </ui:define>

</ui:composition>
</html>

examples/deltaspike-fullstack/src/main/webapp/pages/index.xhtml
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/layout/main-template.xhtml">

    <ui:define name="content">
        <h2>Illustrated Features</h2>
        <h3>Apache DeltaSpike</h3>
        <ul>
            <li>Type-safe view-config</li>
            <li>Type-safe (custom) view-meta-data</li>
            <li>Type-safe navigation</li>
            <li>Type-safe custom project-stage</li>
            <li>@WindowScoped</li>
            <li>@GroupedConversationScoped</li>
            <li>Manual conversation handling</li>
            <li>Secured pages (AccessDecisionVoter)</li>
            <li>@Transactional</li>
            <li>I18n (type-safe messages)</li>
            <li>Dependency-Injection for JSR303 (BV) constraint-validators</li>
            <li>Dependency-Injection for JSF phase-listeners</li>
        </ul>

        <h3>Apache MyFaces ExtVal</h3>
        <ul>
            <li>Cross-Field validation (@Equals)</li>
            <li>Type-safe group-validation (@BeanValidation) for JSF action-methods</li>
        </ul>

        <h2>Hints</h2>
        <ul>
            <li>
                This application doesn't show the/a best practise. It's only a small application which shows a bunch of features.
            </li>
            <li>
                To sync the project-stage of DeltaSpike and JSF use e.g. faces.PROJECT_STAGE=Development in [tomee dir]/conf/system.properties
            </li>
        </ul>
    </ui:define>

</ui:composition>
</html>

examples/deltaspike-fullstack/src/main/webapp/pages/login.xhtml
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/layout/main-template.xhtml">

    <ui:define name="content">
        <h:panelGrid columns="3">
            <h:outputLabel for="loginName" value="#{i18n.lblLoginName}: "/>
            <h:inputText id="loginName" label="#{i18n.lblLoginName}" value="#{registrationPage.user.userName}" required="true"/>
            <h:message for="loginName" showSummary="true" showDetail="false"/>

            <h:outputLabel for="password" value="#{i18n.lblPassword}: "/>
            <h:inputSecret id="password" label="#{i18n.lblPassword}" value="#{registrationPage.user.password}"/>
            <h:message for="password" showSummary="true" showDetail="false"/>
        </h:panelGrid>
        <p/>
        <h:panelGrid columns="2">
            <h:commandButton id="login" value="#{i18n.btnLogin}" action="#{registrationPage.login}"/>
            <h:commandLink id="register" value="#{i18n.btnRegister}" action="#{menuBean.register}" immediate="true"/>
        </h:panelGrid>
    </ui:define>

</ui:composition>
</html>

examples/deltaspike-fullstack/src/main/webapp/pages/registration.xhtml
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                template="/layout/main-template.xhtml">

    <ui:define name="content">
        <h:panelGrid columns="3">
            <h:outputLabel for="firstName" value="#{i18n.lblFirstName}: "/>
            <h:inputText id="firstName" label="#{i18n.lblFirstName}" value="#{registrationPage.user.firstName}"/>
            <h:message for="firstName" showSummary="true" showDetail="false"/>

            <h:outputLabel for="lastName" value="#{i18n.lblLastName}: "/>
            <h:inputText id="lastName" label="#{i18n.lblLastName}" value="#{registrationPage.user.lastName}"/>
            <h:message for="lastName" showSummary="true" showDetail="false"/>

            <h:outputLabel for="loginName" value="#{i18n.lblLoginName}: "/>
            <h:inputText id="loginName" label="#{i18n.lblLoginName}" value="#{registrationPage.user.userName}" required="true"/>
            <h:message for="loginName" showSummary="true" showDetail="false"/>

            <h:outputLabel for="password" value="#{i18n.lblPassword}: "/>
            <h:inputSecret id="password" label="#{i18n.lblPassword}" value="#{registrationPage.user.password}"/>
            <h:message for="password" showSummary="true" showDetail="false"/>

            <h:outputLabel for="repeatedPassword" value="#{i18n.lblRepeatedPassword}: "/>
            <h:inputSecret id="repeatedPassword" label="#{i18n.lblRepeatedPassword}" value="#{registrationPage.repeatedPassword}"/>
            <h:message for="repeatedPassword" showSummary="true" showDetail="false"/>
        </h:panelGrid>
        <p/>
        <h:commandButton id="register" value="#{i18n.btnRegister}" action="#{registrationPage.register}"/>
    </ui:define>

</ui:composition>
</html>